/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeekendGetawaysRouteImport } from './routes/weekend-getaways'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'
import { Route as AdminTripsRouteImport } from './routes/admin.trips'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminTripsIndexRouteImport } from './routes/admin.trips.index'
import { Route as ApiPublicTripsRouteImport } from './routes/api/public/trips'
import { Route as AdminTripsNewRouteImport } from './routes/admin.trips.new'
import { Route as AdminTripsImportRouteImport } from './routes/admin.trips.import'
import { Route as ApiPublicTripsSlugRouteImport } from './routes/api/public/trips.$slug'
import { Route as AdminTripsIdEditRouteImport } from './routes/admin.trips.$id.edit'

const WeekendGetawaysRoute = WeekendGetawaysRouteImport.update({
  id: '/weekend-getaways',
  path: '/weekend-getaways',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsIndexRoute = AdminTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTripsRoute,
} as any)
const ApiPublicTripsRoute = ApiPublicTripsRouteImport.update({
  id: '/api/public/trips',
  path: '/api/public/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTripsNewRoute = AdminTripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTripsRoute,
} as any)
const AdminTripsImportRoute = AdminTripsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminTripsRoute,
} as any)
const ApiPublicTripsSlugRoute = ApiPublicTripsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicTripsRoute,
} as any)
const AdminTripsIdEditRoute = AdminTripsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminTripsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/enquire': typeof EnquireRoute
  '/weekend-getaways': typeof WeekendGetawaysRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/trips/$slug': typeof TripsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/admin/trips/import': typeof AdminTripsImportRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/api/public/trips': typeof ApiPublicTripsRouteWithChildren
  '/admin/trips/': typeof AdminTripsIndexRoute
  '/admin/trips/$id/edit': typeof AdminTripsIdEditRoute
  '/api/public/trips/$slug': typeof ApiPublicTripsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/enquire': typeof EnquireRoute
  '/weekend-getaways': typeof WeekendGetawaysRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/trips': typeof TripsIndexRoute
  '/admin/trips/import': typeof AdminTripsImportRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/api/public/trips': typeof ApiPublicTripsRouteWithChildren
  '/admin/trips': typeof AdminTripsIndexRoute
  '/admin/trips/$id/edit': typeof AdminTripsIdEditRoute
  '/api/public/trips/$slug': typeof ApiPublicTripsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/enquire': typeof EnquireRoute
  '/weekend-getaways': typeof WeekendGetawaysRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/trips/$slug': typeof TripsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/admin/trips/import': typeof AdminTripsImportRoute
  '/admin/trips/new': typeof AdminTripsNewRoute
  '/api/public/trips': typeof ApiPublicTripsRouteWithChildren
  '/admin/trips/': typeof AdminTripsIndexRoute
  '/admin/trips/$id/edit': typeof AdminTripsIdEditRoute
  '/api/public/trips/$slug': typeof ApiPublicTripsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/enquire'
    | '/weekend-getaways'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/trips'
    | '/trips/$slug'
    | '/admin/'
    | '/trips/'
    | '/admin/trips/import'
    | '/admin/trips/new'
    | '/api/public/trips'
    | '/admin/trips/'
    | '/admin/trips/$id/edit'
    | '/api/public/trips/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/enquire'
    | '/weekend-getaways'
    | '/admin/enquiries'
    | '/admin/login'
    | '/trips/$slug'
    | '/admin'
    | '/trips'
    | '/admin/trips/import'
    | '/admin/trips/new'
    | '/api/public/trips'
    | '/admin/trips'
    | '/admin/trips/$id/edit'
    | '/api/public/trips/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/enquire'
    | '/weekend-getaways'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/trips'
    | '/trips/$slug'
    | '/admin/'
    | '/trips/'
    | '/admin/trips/import'
    | '/admin/trips/new'
    | '/api/public/trips'
    | '/admin/trips/'
    | '/admin/trips/$id/edit'
    | '/api/public/trips/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRouteWithChildren
  EnquireRoute: typeof EnquireRoute
  WeekendGetawaysRoute: typeof WeekendGetawaysRoute
  TripsSlugRoute: typeof TripsSlugRoute
  TripsIndexRoute: typeof TripsIndexRoute
  ApiPublicTripsRoute: typeof ApiPublicTripsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekend-getaways': {
      id: '/weekend-getaways'
      path: '/weekend-getaways'
      fullPath: '/weekend-getaways'
      preLoaderRoute: typeof WeekendGetawaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips/': {
      id: '/admin/trips/'
      path: '/'
      fullPath: '/admin/trips/'
      preLoaderRoute: typeof AdminTripsIndexRouteImport
      parentRoute: typeof AdminTripsRoute
    }
    '/api/public/trips': {
      id: '/api/public/trips'
      path: '/api/public/trips'
      fullPath: '/api/public/trips'
      preLoaderRoute: typeof ApiPublicTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trips/new': {
      id: '/admin/trips/new'
      path: '/new'
      fullPath: '/admin/trips/new'
      preLoaderRoute: typeof AdminTripsNewRouteImport
      parentRoute: typeof AdminTripsRoute
    }
    '/admin/trips/import': {
      id: '/admin/trips/import'
      path: '/import'
      fullPath: '/admin/trips/import'
      preLoaderRoute: typeof AdminTripsImportRouteImport
      parentRoute: typeof AdminTripsRoute
    }
    '/api/public/trips/$slug': {
      id: '/api/public/trips/$slug'
      path: '/$slug'
      fullPath: '/api/public/trips/$slug'
      preLoaderRoute: typeof ApiPublicTripsSlugRouteImport
      parentRoute: typeof ApiPublicTripsRoute
    }
    '/admin/trips/$id/edit': {
      id: '/admin/trips/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/trips/$id/edit'
      preLoaderRoute: typeof AdminTripsIdEditRouteImport
      parentRoute: typeof AdminTripsRoute
    }
  }
}

interface AdminTripsRouteChildren {
  AdminTripsImportRoute: typeof AdminTripsImportRoute
  AdminTripsNewRoute: typeof AdminTripsNewRoute
  AdminTripsIndexRoute: typeof AdminTripsIndexRoute
  AdminTripsIdEditRoute: typeof AdminTripsIdEditRoute
}

const AdminTripsRouteChildren: AdminTripsRouteChildren = {
  AdminTripsImportRoute: AdminTripsImportRoute,
  AdminTripsNewRoute: AdminTripsNewRoute,
  AdminTripsIndexRoute: AdminTripsIndexRoute,
  AdminTripsIdEditRoute: AdminTripsIdEditRoute,
}

const AdminTripsRouteWithChildren = AdminTripsRoute._addFileChildren(
  AdminTripsRouteChildren,
)

interface AdminRouteChildren {
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTripsRoute: typeof AdminTripsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminTripsRoute: AdminTripsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiPublicTripsRouteChildren {
  ApiPublicTripsSlugRoute: typeof ApiPublicTripsSlugRoute
}

const ApiPublicTripsRouteChildren: ApiPublicTripsRouteChildren = {
  ApiPublicTripsSlugRoute: ApiPublicTripsSlugRoute,
}

const ApiPublicTripsRouteWithChildren = ApiPublicTripsRoute._addFileChildren(
  ApiPublicTripsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRouteWithChildren,
  EnquireRoute: EnquireRoute,
  WeekendGetawaysRoute: WeekendGetawaysRoute,
  TripsSlugRoute: TripsSlugRoute,
  TripsIndexRoute: TripsIndexRoute,
  ApiPublicTripsRoute: ApiPublicTripsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
